#!/usr/bin/env python3
"""
The Hat-Spectre monotile family, exactly.

    python3 examples/monotile.py
    python3 examples/monotile.py --only localizer --rings 1

In 2023 a single 13-sided shape -- the Hat -- was shown to tile the plane
only aperiodically, and recent work puts quantum models on the vertices of
its whole family Tile(a,b) and uses the shape parameter as a control knob for
the quantum geometric tensor. An aperiodic tiling has no Brillouin zone, so
its topology must be computed in real space, and the real-space invariant of
choice is *the signature of a matrix*. A signature is decidable exactly over
an ordered field. That is the whole premise of this module.

    1  the family     named tiles at exact parameter values, and the mirror
                      that pairs the Hat with the Turtle and fixes the Spectre
    2  inflation      the Perron eigenvalue phi^4, as a root of an exactly
                      computed characteristic polynomial
    3  chirality      the hat : anti-hat ratio phi^4 : 1, derived, and
                      aperiodicity from the irrationality of an eigenvector
    4  the substrate  the Laves kite lattice, whose vertex count detects the
                      Hat's proportions
    5  localizer      the spectral localizer index over Q(sqrt3): topological
                      phases located with no floating point anywhere

Everything printed is an exact element of Q(sqrt3) or Q(sqrt5); the floats in
parentheses are for orientation only and enter no computation.
"""

import argparse
import sys
import time
from fractions import Fraction as F

sys.path.insert(0, __file__.rsplit("/", 2)[0])

from pyCICY import monotile as MT
from pyCICY.monotile import Quad, SQRT3


def banner(text):
    print("\n" + text)
    print("-" * len(text))


def family():
    banner("1. The family, by parameter")

    print("""\
Tile(a,b) depends on two edge lengths only through ell = a/(a+b). Exchanging
a and b reflects the tile, so ell -> 1-ell is a mirror on the family.
""")
    t = MT.named_tiles()
    for name in ("Chevron", "Hat", "Spectre", "Turtle", "Comet"):
        v = t[name]
        print("  %-9s ell = %-22s ~ %.6f" % (name, v, float(v)))
    print()
    print("  Hat + Turtle           = %s   (a mirror pair)"
          % (t["Hat"] + t["Turtle"]))
    print("  mirror(Spectre)        = %s   (the fixed point)"
          % MT.mirror_ell(t["Spectre"]))
    print("""
The Spectre sitting at the mirror's fixed point is the parameter-space shadow
of its special role: it is the member that tiles with a single handedness,
the 'vampire einstein' that casts no reflection. The Hat needs its mirror
image -- but only just, as section 3 quantifies.""")


def inflation():
    banner("2. The inflation factor, derived")

    r = MT.inflation_factor()
    print("""\
The Hat tiling is generated by four metatiles H, T, P, F and a substitution
rule. The substitution matrix is quoted from Smith, Myers, Kaplan and
Goodman-Strauss; its characteristic polynomial is computed over the integers
by exact Leverrier-Faddeev, with nothing numerical:
""")
    print("  charpoly  %s   =  (x^2 - 7x + 1)(x^2 - 1)" % (r["charpoly"],))
    print("  Perron eigenvalue  %s  ~ %.6f" % (r["value"], float(r["value"])))
    print("  verified as an exact root: %s;  satisfies x^2 = 7x - 1: %s"
          % (r["is_root"], r["is_phi4"]))
    print("""
So one inflation step multiplies areas by phi^4, the fourth power of the
golden ratio -- an exact element of Q(sqrt5), not a fitted number. Its
Galois conjugate phi^-4 is the other root of the same quadratic, and their
product is the constant term, one.""")


def chirality():
    banner("3. Chirality and aperiodicity, from an eigenvector")

    f = MT.metatile_frequencies()
    print("  metatile frequencies (Perron eigenvector over Q(sqrt5)):")
    for name in MT.METATILES:
        print("    %-3s %-24s ~ %.6f" % (name, f[name], float(f[name])))
    c = MT.hat_chirality()
    print()
    print("  every anti-hat lives in an H supertile (one of its four hats),")
    print("  so weighting by the hat counts gives")
    print()
    print("    unreflected : reflected = %s : 1   ~ %.4f"
          % (c["ratio"], float(c["ratio"])))
    print("    which is phi^4 exactly: %s" % c["is_phi4"])
    print("    reflected fraction = %s = 1/(1 + phi^4)"
          % c["reflected_fraction"])
    a = MT.is_aperiodic()
    print("""
Aperiodicity follows from the same eigenvector. A tiling with a period has a
fundamental domain, hence rational tile frequencies; the %s frequency has
irrational part %s, so no period exists. The headline fact about the Hat is,
at this level of description, the irrationality of an eigenvector -- the same
shape of argument that quasicrystal diffraction rests on.""" % (
        a["witness"], a["irrational_part"]))


def substrate():
    banner("4. The Laves substrate, and where the Hat sits in it")

    print("""\
Every Tile(a,b) is a union of eight kites whose two bond lengths are the
parameters: hexagon centre to edge midpoint (a), and edge midpoint to hexagon
vertex (b), meeting at right angles along directions that are multiples of
30 degrees. All coordinates therefore live in Q(sqrt3).
""")
    for a, b, label in ((Quad(1, 0, 3), Quad(1, 0, 3), "a : b = 1 : 1"),
                        (SQRT3, Quad(1, 0, 3), "a : b = sqrt3 : 1"),
                        (Quad(F(17, 10), 0, 3), Quad(1, 0, 3),
                         "a : b = 1.7 : 1")):
        p = MT.laves_patch(a=a, b=b, rings=0)
        print("  %-20s %2d sites  (%d centre, %d edge, %d vertex)"
              % (label, len(p["sites"]), p["kind"].count("centre"),
                 p["kind"].count("edge"), p["kind"].count("vertex")))
    print("""
The middle line is the detection: at a : b = sqrt3 : 1 -- the Hat's
proportions, and only there -- the twelve outer corners merge in pairs into
the six vertices of the [3.4.6.4] Laves tiling. Whether two exact coordinates
coincide is decided by the order on Q(sqrt3), not by a tolerance, and 1.7 is
close to sqrt3 but the sites do not merge.

The patch is periodic, and the module says so: generating genuine aperiodic
vertex patches needs the substitution geometry, which is not implemented.
What the patch supplies is the local geometry every Tile(a,b) model inherits,
and a testbed for the machinery of section 5.""")


def localizer(rings):
    banner("5. The spectral localizer, with no floating point")

    print("""\
A two-orbital Chern-insulator model (Qi-Wu-Zhang transplanted to the graph)
is placed on the patch. The local topological index at a point is half the
signature of the spectral localizer

    L = [[ H - E,     kappa Pi ],          Pi = (X - x0) - i (Y - y0)
         [ kappa Pi+, -(H - E) ]]

and a signature is a count of pivot signs in an LDL^T decomposition --
computable exactly over the ordered field Q(sqrt3), with no eigenvalue ever
taken. Scanning the mass term:
""")
    t0 = time.time()
    scan = MT.phase_scan([F(-4), F(-1), F(1, 2), F(4)], rings=rings)
    for M, idx in scan:
        label = {0: "trivial", 1: "topological, C = +1",
                 -1: "topological, C = -1"}.get(idx, "gap closed")
        print("    M = %-5s ->  index %2s   %s" % (M, idx, label))
    print("""
  (%.1fs, every step exact)

The index jumps between the sampled masses, so each jump brackets an exact
topological transition -- located without a band structure, because there is
none to compute: the system this machinery is built for has no Brillouin
zone. The tests additionally check the exact signature against a numpy
eigenvalue count of the same matrix: one route is field arithmetic, the
other is LAPACK, and they agree on every mass.""" % (time.time() - t0))


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--only", default=None,
                   choices=["family", "inflation", "chirality", "substrate",
                            "localizer"])
    p.add_argument("--rings", type=int, default=0,
                   help="patch size for the localizer section")
    a = p.parse_args()

    sections = {"family": family, "inflation": inflation,
                "chirality": chirality, "substrate": substrate,
                "localizer": lambda: localizer(a.rings)}
    order = ["family", "inflation", "chirality", "substrate", "localizer"]
    for key in ([a.only] if a.only else order):
        sections[key]()
    print()


if __name__ == "__main__":
    main()
