#!/usr/bin/env python3
"""
Survey the conifold web generated by splitting.

Starts from the five Calabi-Yau threefolds cut out by a single equation and
applies P^1 splits repeatedly, which is how the CICY threefold list was
originally compiled:

    P. Candelas, A. M. Dale, C. A. Lutken, R. Schimmrigk,
    "Complete Intersection Calabi-Yau Manifolds",
    Nucl. Phys. B298 (1988) 493.

Each split is the resolution side of a conifold transition, and the node
count N of the shared singular variety is recorded for every edge, following
section 1.1 of

    L. B. Anderson, J. Gray, S. A. Patil, C. Scanlon,
    "Mapping moduli across heterotic conifolds", arXiv:2512.18124.

Hodge data is memoised in /tmp (see pyCICY.cache), so re-running this to
adjust a plot costs almost nothing after the first pass.

Usage
-----
    python3 examples/split_survey.py --depth 3 --out /tmp
    python3 examples/split_survey.py --depth 3 --no-cache   # timing check
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pyCICY import cache as C
from pyCICY import cicylist as L


LANDMARKS = [
    (1.0, 101.0, "quintic"),
    (2.0, 86.0, "split quintic"),
    (19.0, 19.0, "Schoen"),
]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    ap.add_argument("--depth", type=int, default=3,
                    help="how many successive splits (default 3)")
    ap.add_argument("--max-configs", type=int, default=1200,
                    help="budget on distinct configurations (default 1200)")
    ap.add_argument("--no-cache", action="store_true",
                    help="bypass the cache, for timing comparisons")
    ap.add_argument("--clear-cache", action="store_true",
                    help="empty the cache before starting")
    ap.add_argument("--out", default=None,
                    help="directory to write plots into")
    args = ap.parse_args(argv)

    cache = C.Cache(enabled=not args.no_cache)
    if args.clear_cache:
        cache.clear()
        print("cache cleared")

    def progress(known, frontier, depth):
        print("  depth %d: %d configurations known, %d new"
              % (depth, known, frontier), flush=True)

    print("generating the split web, depth %d" % args.depth)
    start = time.time()
    web = L.split_web(max_depth=args.depth, max_configs=args.max_configs,
                      cache=cache, progress=progress)
    elapsed = time.time() - start

    stats = web["stats"]
    survey = L.survey(web)

    print("\n%-28s %s" % ("configurations", survey["configurations"]))
    print("%-28s %s" % ("split edges", stats["edges"]))
    print("%-28s %s" % ("  effective (N > 0)", stats["effective_edges"]))
    print("%-28s %s" % ("  ineffective (N = 0)", stats["ineffective_edges"]))
    print("%-28s %s" % ("distinct Hodge pairs", survey["distinct_hodge_pairs"]))
    print("%-28s %s" % ("favourable descriptions", survey["favourable"]))
    print("%-28s %s" % ("h^{1,1} range", survey["h11_range"]))
    print("%-28s %s" % ("h^{2,1} range", survey["h21_range"]))
    print("%-28s %s" % ("chi range", survey["euler_range"]))
    print("%-28s %s" % ("by depth", survey["by_depth"]))
    if stats["truncated"]:
        print("\nNOTE: stopped at the --max-configs budget; this is a sample "
              "of the web at this depth, not all of it.")

    c = stats["cache"]
    print("\n%-28s %d hits, %d misses (%.0f%% hit rate)"
          % ("cache", c["hits"], c["misses"], 100 * c["hit_rate"]))
    print("%-28s %.1fs" % ("elapsed", elapsed))
    if not args.no_cache:
        stored = cache.info()
        print("%-28s %s" % ("cache file", stored["path"]))
        print("%-28s %.1fs of compute stored"
              % ("", stored["seconds_stored"]))

    # The edge from arXiv:2512.18124 section 1.1, if the depth reached it.
    from pyCICY import transitions as T
    qk = T.canonical_key([[4, 5]])
    sk = T.canonical_key([[1, 1, 1], [4, 1, 4]])
    edge = [e for e in web["edges"] if e["parent"] == qk and e["child"] == sk]
    if edge:
        print("\nquintic -> [[1,1,1],[4,1,4]]: N = %d nodes "
              "(arXiv:2512.18124 quotes 16)" % edge[0]["nodes"])

    biggest = sorted(web["edges"], key=lambda e: -e["nodes"])[:5]
    print("\nsplits with the most nodes:")
    for e in biggest:
        print("   N = %-5d partition %s of equation %d"
              % (e["nodes"], e["partition"], e["column"]))

    if args.out:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from pyCICY import viz

        os.makedirs(args.out, exist_ok=True)
        fig = plt.figure(figsize=(16, 6))
        ax1 = fig.add_subplot(1, 2, 1)
        viz.plot_hodge(L.web_nodes(web), ax=ax1, color_by="depth",
                       annotate=LANDMARKS)
        ax2 = fig.add_subplot(1, 2, 2)
        viz.plot_node_counts(web["edges"], ax=ax2)
        fig.tight_layout()
        path = os.path.join(args.out, "split_survey.png")
        fig.savefig(path, dpi=120, bbox_inches="tight")
        print("\nwrote %s" % path)

        ax = viz.plot_hodge(L.web_nodes(web), color_by="favourable",
                            annotate=LANDMARKS)
        path = os.path.join(args.out, "split_survey_favourable.png")
        ax.figure.savefig(path, dpi=120, bbox_inches="tight")
        print("wrote %s" % path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
