r"""
pyCICY.theories.hopf -- the complex six-sphere as a registry entry.

The mathematics lives in :mod:`pyCICY.sixsphere`. This class exists so that
one lookup in :data:`~.base.registry` answers the question a string theorist
will ask first: *can you compactify on it?*

The answer is a ledger entry of the third kind, not the second. Nothing is
waiting on a metric. By item (7) of Alpoge's main theorem the canonical
bundle is K_X = f^*O(-1) (x) O_X(2 S_2), which is not torsion in Pic(X); so X
carries no nowhere-vanishing holomorphic 3-form, and no power of K_X is
trivial either. Every four-dimensional N = 1 vacuum this package knows how to
describe on a complex threefold -- Calabi-Yau, and the non-Kahler heterotic
backgrounds of the Strominger system -- needs exactly that form. And b_2 = 0
excludes a Kahler metric outright. So the spectrum is not unknown; there is
no such compactification, and :exc:`~.ftheory.NoSuchTheory` says so.

One contrast worth keeping visible. String theory already uses S^6, as the
nearly-Kahler coset G_2/SU(3), whose almost complex structure is the
octonionic one and is *not* integrable. The new structure is integrable and
unrelated: it is not produced from any metric, and LeBrun's theorem forbids
it from being orthogonal for the round one. Nothing about the old
compactifications transfers.

The K_X statement is quoted from the paper (Theorem 9.1 (iii)). What is
computed, in :func:`pyCICY.sixsphere.picard_arithmetic`, is that it is not
torsion: in the subgroup of Pic(X) generated by f^*O(1) and the two
multiple-fibre reductions, which is infinite cyclic, K_X is -6 times the
generator.
"""

from .base import Theory, register
from .ftheory import NoSuchTheory

__all__ = ["ComplexSixSphere"]

_NO_VACUUM = (
    "X has no nowhere-vanishing holomorphic 3-form: K_X = f^*O(-1) (x) "
    "O_X(2 S_2) is not torsion (Alpoge, Main Theorem (7)), and b_2(X) = 0 "
    "excludes a Kahler metric. A Calabi-Yau or Strominger-system "
    "compactification needs that form, so there is no four-dimensional "
    "vacuum here to have a spectrum. This is an absence, not a missing "
    "computation.")


@register
class ComplexSixSphere(Theory):
    """Alpoge's torus-fibred threefold X, diffeomorphic to S^6.

    ``X = None``: the manifold is not a CICY, not Kahler, not even
    Moishezon. The exact content is the lattice layer in
    :mod:`pyCICY.sixsphere`; the physics verbs all raise
    :exc:`~pyCICY.theories.ftheory.NoSuchTheory`.
    """

    key = "complex-six-sphere"

    def __init__(self, name=None):
        Theory.__init__(self, None, name=name)

    def geometry(self):
        return ("a compact complex threefold fibred by 2-tori over P^1, with "
                "fibres dP6/~ and bielliptic x3, x4 over three points; "
                "diffeomorphic to S^6 (Alpoge 2026)")

    def gauge_group(self):
        return "none (a complex manifold with no N = 1 vacuum on it)"

    def spectrum(self):
        raise NoSuchTheory(_NO_VACUUM)

    def holomorphic_yukawa(self, **kw):
        raise NoSuchTheory(_NO_VACUUM)

    def physical_yukawa(self, **kw):
        # The base class blames the metric. Here that would be the wrong
        # ledger entry: there is no coupling to normalise.
        raise NoSuchTheory(_NO_VACUUM)

    def fermion_masses(self, **kw):
        raise NoSuchTheory(_NO_VACUUM)

    def missing_for_physical(self):
        return []

    def lattice(self):
        """The exact lattice layer: :func:`pyCICY.sixsphere.status`."""
        from .. import sixsphere
        return sixsphere.status()

    def cusp(self):
        """The toric filling: :func:`pyCICY.sixsphere.status_cusp`."""
        from .. import sixsphere
        return sixsphere.status_cusp()

    def lean(self, lean_path=None):
        """The machine-checked grade: :func:`pyCICY.sixsphere_lean.status`.

        Needs a ``lean`` on PATH or in PYCICY_LEAN; without one it reports
        every fact as computed and none as machine-checked.
        """
        from .. import sixsphere_lean
        return sixsphere_lean.status(lean_path=lean_path)

    def invariants(self):
        """Topology and invariants: :func:`pyCICY.sixsphere.status_invariants`."""
        from .. import sixsphere
        return sixsphere.status_invariants()

    def periods(self):
        """The period-law identities: :func:`pyCICY.sixsphere.status_periods`."""
        from .. import sixsphere
        return sixsphere.status_periods()

    def exact_content(self):
        return [
            "the monodromy representation of the (3,4,inf) triangle group "
            "on Z^4: orders, unipotent cusp, fixed and invariant lattices",
            "the unique invariant alternating form Q0 and bivector eta, "
            "solved separately, with eta = *Q0 and eta^2 = 12",
            "b = Q0(., N .) = diag(6, -1): the degeneration has no "
            "polarisation",
            "|det B0| = 1, which makes the cusp fibre a single dP6",
            "freeness of the logarithmic transforms, derived",
            "|p| as the order of H_1 of the (3,4) Seifert space, against the "
            "paper's closed form",
            "the transformation laws of the period functions tau, mu, beta, "
            "as symbolic identities, and re-derived from T1, T2 alone",
            "det_R Pi = Im tau * D, the invariance of D, and the Hodge form "
            "on F^1 with signature (1, 1)",
            "the rational elliptic surface behind tau: IV*, III, I_1, by "
            "ftheory on the Weierstrass orders and independently by the "
            "lattice subquotient with Noether's formula",
            "the toric filling at the cusp: unimodular A2 fan, the dP6 "
            "component, opposite sides glued, two triple points, e(W) = 2 "
            "two ways, Friedman's triple-point formula, and e(W) = 2d for "
            "|det B0| = d",
            "H_1(X) = Z/|p| from the full presentation of Theorem 7.17, the "
            "Betti numbers of W and of the cusp boundary from exterior powers "
            "of the monodromy, and the multiple fibres' indices",
            "chi(O, Omega^p, T) by Hirzebruch-Riemann-Roch; chi(O) = 0 two "
            "ways; the Hodge numbers up to the one open integer h^{1,2}",
            "K_X = -6u in Pic: not torsion, and the classical multiple-fibre "
            "formula impossible; deg f_* omega = 1 two ways; the C^* fixed "
            "curve and its weights (+1, -1)",
            "30 facts of the finite layer machine-checked by the Lean 4 "
            "kernel, Mathlib-free, on Lean's standard axioms (see lean())",
        ]

    def declined(self):
        return [
            "the spectrum, Yukawa couplings and masses: no such "
            "compactification (NoSuchTheory)",
            "that pi_1(X) is abelian and the presentation itself: van "
            "Kampen over the pieces (Theorem 7.17, quoted)",
            "h^{1,2}: not computed in the paper either (Remark 9.21)",
            "the direct images of O_X, h^{p,0} = 0 and a(X) = 1: analysis on "
            "the fibres (quoted from Theorem 9.1)",
            "existence of tau, mu, beta and a c0 with D < 0: lifting and "
            "torsor arguments, true by argument (NotAnalytic)",
            "freeness, proper discontinuity and properness of the toric "
            "quotient at the cusp: analytic estimates (NotAnalytic)",
            "X diffeomorphic to S^6: topology and analysis; machine-checked "
            "externally (github.com/plby/HopfProblem), not re-run here",
        ]

    def describe(self):
        lines = ["%s on %s" % (self.name, self.geometry()),
                 "  gauge group      %s" % self.gauge_group(),
                 "  exact:"]
        lines += ["     - %s" % e for e in self.exact_content()]
        lines.append("  declined:")
        lines += ["     - %s" % d for d in self.declined()]
        return "\n".join(lines)
