r"""
pyCICY.smoothness -- the Jacobian rank criterion for complete intersections.

Following section 2.2 of

    L. B. Anderson, A. Constantin, J. Gray, Y.-H. He, S.-J. Lee, A. Lukas,
    "CIPro Package: Complete Intersections in Products of Projective Spaces
    and Line Bundles", arXiv:2606.27588,

a complete intersection X cut out by s_1, ..., s_r is smooth exactly when the
differentials ds_a are linearly independent at every point of X, equivalently

    rank ( d s_a / d x^{(i)}_j )_{a; i,j} = r   for all x in X .

Where the differentials drop rank on X, the variety is singular.

What this module actually decides
---------------------------------
Deciding the criterion over the complex numbers means showing that the ideal
generated by the equations together with all r x r minors of the Jacobian
defines the empty set away from the irrelevant locus. That is an elimination
problem and wants a Grobner basis engine; it is not implemented here.

Instead, the criterion is checked **exhaustively over a finite field**: every
point of P^{n_1}(F_p) x ... x P^{n_m}(F_p) is enumerated and tested. This is
rigorous about the reduction of X modulo p, and that is how the results are
reported:

* a singular point found over F_p is a genuine singular point of the
  reduction, and for equations with integer coefficients whose singular locus
  is defined over the prime field it is strong evidence of singularity in
  characteristic zero;
* finding none over several primes is evidence of smoothness, **not a proof**.

:func:`is_smooth` says which of these it is doing in its return value rather
than presenting either as a theorem.

Two traps that the finite field approach walks into, both handled explicitly:

* if p divides a degree, formal derivatives vanish identically and everything
  looks singular. The Fermat quintic is "singular" over F_5 for this reason
  alone. :func:`is_smooth` refuses such primes by default.
* the point count grows as prod (p^{n_i+1} - 1)/(p - 1) and becomes
  impractical for large ambient spaces, so there is a budget and an explicit
  refusal rather than an unbounded run.
"""

import itertools as it
import random

from .transitions import _as_matrix, dimensions

__all__ = [
    "coordinate_layout", "monomials", "random_equations", "monomial_string",
    "singular_points", "is_smooth",
]


# ------------------------------------------------------------------ layout

def coordinate_layout(conf):
    """Return ``(dims, slices, n_vars)`` describing the ambient coordinates.

    ``slices[i]`` is the ``(start, stop)`` range of coordinate indices
    belonging to the i-th projective factor, which has ``dims[i] + 1``
    homogeneous coordinates.
    """
    M = _as_matrix(conf)
    dims = [int(M[i, 0]) for i in range(M.shape[0])]
    slices = []
    start = 0
    for n in dims:
        slices.append((start, start + n + 1))
        start += n + 1
    return dims, slices, start


def monomials(conf, multidegree):
    """All monomials of the given multidegree, as exponent tuples.

    The exponent tuple runs over every ambient coordinate; within the i-th
    projective factor the exponents sum to ``multidegree[i]``.
    """
    dims, slices, n_vars = coordinate_layout(conf)
    if len(multidegree) != len(dims):
        raise ValueError("multidegree needs one entry per projective factor")

    per_factor = []
    for i, (lo, hi) in enumerate(slices):
        width = hi - lo
        per_factor.append(list(_compositions(int(multidegree[i]), width)))

    out = []
    for combo in it.product(*per_factor):
        expo = []
        for part in combo:
            expo.extend(part)
        out.append(tuple(expo))
    return out


def _compositions(total, parts):
    """Weak compositions of ``total`` into ``parts`` non-negative pieces."""
    if parts == 1:
        yield (total,)
        return
    for first in range(total + 1):
        for rest in _compositions(total - first, parts - 1):
            yield (first,) + rest


def monomial_string(expo, names=None):
    """Render an exponent tuple, e.g. ``x0 y1`` or ``x0^2 z1``."""
    names = names or ["v%d" % i for i in range(len(expo))]
    parts = []
    for i, k in enumerate(expo):
        if k == 1:
            parts.append(names[i])
        elif k > 1:
            parts.append("%s^%d" % (names[i], k))
    return " ".join(parts) if parts else "1"


def default_names(conf):
    """Conventional coordinate names: x, y, z, ... per projective factor."""
    dims, slices, _ = coordinate_layout(conf)
    letters = "xyzuvwstpqrabcdefghijklmno"
    names = []
    for i, n in enumerate(dims):
        letter = letters[i] if i < len(letters) else "c%d" % i
        names.extend(["%s%d" % (letter, j) for j in range(n + 1)])
    return names


# --------------------------------------------------------------- equations

def random_equations(conf, p, seed=0, dense=True):
    """Generic defining equations with random coefficients over F_p.

    Each equation is a dict mapping exponent tuple to coefficient. One
    equation is produced per column of the configuration, with the column's
    multidegree.
    """
    M = _as_matrix(conf)
    kk = M.shape[1] - 1
    rng = random.Random(seed)

    equations = []
    for c in range(kk):
        q = [int(M[i, 1 + c]) for i in range(M.shape[0])]
        terms = {}
        for expo in monomials(M, q):
            coeff = rng.randrange(p) if dense else (
                rng.randrange(p) if rng.random() < 0.5 else 0)
            if coeff % p:
                terms[expo] = coeff % p
        if not terms:                      # never hand back the zero equation
            expo = monomials(M, q)[0]
            terms[expo] = 1
        equations.append(terms)
    return equations


def _evaluate(poly, point, p):
    total = 0
    for expo, coeff in poly.items():
        term = coeff % p
        if term == 0:
            continue
        for i, k in enumerate(expo):
            if k:
                term = (term * pow(point[i], k, p)) % p
                if term == 0:
                    break
        total = (total + term) % p
    return total


def _derivative(poly, var):
    """Formal derivative of a polynomial with respect to one coordinate."""
    out = {}
    for expo, coeff in poly.items():
        k = expo[var]
        if k == 0:
            continue
        new = list(expo)
        new[var] = k - 1
        key = tuple(new)
        out[key] = out.get(key, 0) + coeff * k
    return out


def _projective_points(n, p):
    """Every point of P^n(F_p), normalised so the first nonzero entry is 1."""
    for pivot in range(n + 1):
        for tail in it.product(range(p), repeat=n - pivot):
            yield (0,) * pivot + (1,) + tail


def _rank_mod_p(rows, p):
    """Rank of a matrix over F_p by Gaussian elimination."""
    mat = [list(r) for r in rows]
    rank = 0
    n_cols = len(mat[0]) if mat else 0
    for col in range(n_cols):
        pivot = None
        for r in range(rank, len(mat)):
            if mat[r][col] % p:
                pivot = r
                break
        if pivot is None:
            continue
        mat[rank], mat[pivot] = mat[pivot], mat[rank]
        inv = pow(mat[rank][col], p - 2, p)
        mat[rank] = [(v * inv) % p for v in mat[rank]]
        for r in range(len(mat)):
            if r != rank and mat[r][col] % p:
                factor = mat[r][col]
                mat[r] = [(a - factor * b) % p
                          for a, b in zip(mat[r], mat[rank])]
        rank += 1
        if rank == len(mat):
            break
    return rank


def point_count(conf, p):
    """Number of points of the ambient space over F_p."""
    dims, _, _ = coordinate_layout(conf)
    total = 1
    for n in dims:
        total *= (p ** (n + 1) - 1) // (p - 1)
    return total


# ------------------------------------------------------------------ search

def singular_points(conf, equations, p, max_points=2000000, limit=None):
    """Find points of X(F_p) where the Jacobian drops rank.

    Exhaustive over the ambient space; rigorous about the reduction mod p.

    Returns
    -------
    dict with ``singular`` (list of points), ``points_on_X``, ``points_scanned``
    and ``rank_required``.
    """
    M = _as_matrix(conf)
    dims, slices, n_vars = coordinate_layout(M)
    r = M.shape[1] - 1

    total = point_count(M, p)
    if total > max_points:
        raise ValueError(
            "ambient space has %d points over F_%d, above the budget of %d. "
            "Exhaustive checking is impractical here; raise max_points if you "
            "are willing to wait, or use a smaller prime."
            % (total, p, max_points))

    derivatives = [[_derivative(eq, v) for v in range(n_vars)]
                   for eq in equations]

    singular = []
    on_x = 0
    scanned = 0
    factors = [list(_projective_points(n, p)) for n in dims]

    for combo in it.product(*factors):
        point = []
        for part in combo:
            point.extend(part)
        scanned += 1

        if any(_evaluate(eq, point, p) for eq in equations):
            continue
        on_x += 1

        jac = [[_evaluate(d, point, p) for d in row] for row in derivatives]
        if _rank_mod_p(jac, p) < r:
            singular.append(tuple(point))
            if limit is not None and len(singular) >= limit:
                break

    return {
        "singular": singular,
        "points_on_X": on_x,
        "points_scanned": scanned,
        "rank_required": r,
    }


def is_smooth(conf, equations=None, primes=(7, 11), seed=0, trials=6,
              max_points=2000000, allow_bad_primes=False):
    """Test the Jacobian rank criterion over one or more finite fields.

    Parameters
    ----------
    equations : list of dict or None
        Explicit defining equations, as exponent-tuple to coefficient maps.
        If None, random equations are generated and the question asked is
        whether a *generic* member of the family is smooth.
    primes : iterable of int
        Primes to reduce modulo. A prime dividing any degree in the
        configuration is rejected, since formal derivatives then vanish and
        every point looks singular; the Fermat quintic over F_5 is the
        standard example.
    trials : int
        Number of random equation sets to try per prime, used only when
        ``equations`` is None. Over a small field a single random draw is
        not reliably generic: it can land on a genuinely singular member.
        Smoothness is an open condition, so exhibiting **one** smooth member
        establishes that the generic member is smooth, and that is the logic
        used. Ignored when explicit equations are supplied, where the
        question is about those equations and nothing else.
    allow_bad_primes : bool
        Use degree-dividing primes anyway, for demonstrating the failure.

    Returns
    -------
    dict
        ``smooth``: for explicit equations, whether any singular point was
        found. For the generic question, whether some member was smooth.
        ``proof``: always False. Absence of singular points over finitely
        many primes is evidence, not a proof in characteristic zero; the
        field is present so callers cannot mistake one for the other.
        ``per_prime``: the detail for each prime.
        ``singular_example``: a witness point when one was found.
    """
    M = _as_matrix(conf)
    degrees = [int(v) for row in M for v in row[1:]]
    generic = equations is None

    per_prime = {}
    witness = None
    any_smooth = False
    any_singular = False
    used = 0

    for p in primes:
        bad = [d for d in degrees if d % p == 0 and d > 0]
        if bad and not allow_bad_primes:
            per_prime[p] = {
                "skipped": "p divides the degrees %s, so formal derivatives "
                           "vanish and the criterion is vacuous"
                           % sorted(set(bad)),
            }
            continue

        n_trials = trials if generic else 1
        smooth_draws = singular_draws = 0
        info = {"trials": n_trials}

        for t in range(n_trials):
            eqs = equations if not generic else random_equations(
                M, p, seed=seed + t)
            try:
                result = singular_points(M, eqs, p, max_points=max_points,
                                         limit=1)
            except ValueError as exc:
                info = {"skipped": str(exc)}
                break

            if result["singular"]:
                singular_draws += 1
                witness = witness or result["singular"][0]
            else:
                smooth_draws += 1
            info["points_on_X"] = result["points_on_X"]
            info["points_scanned"] = result["points_scanned"]

        if "skipped" in info:
            per_prime[p] = info
            continue

        used += 1
        info["smooth_draws"] = smooth_draws
        info["singular_draws"] = singular_draws
        per_prime[p] = info
        any_smooth = any_smooth or smooth_draws > 0
        any_singular = any_singular or singular_draws > 0

    if used == 0:
        return {
            "smooth": None,
            "proof": False,
            "reason": "no usable prime; see per_prime for why",
            "per_prime": per_prime,
            "singular_example": None,
            "generic": generic,
        }

    if generic:
        smooth = any_smooth
        reason = ("a smooth member was exhibited, so the generic member is "
                  "smooth (evidence over finite fields, not a proof in "
                  "characteristic zero)" if smooth else
                  "every random member tried was singular over %d prime(s), "
                  "suggesting the whole family is singular" % used)
    else:
        smooth = not any_singular
        reason = ("a singular point was found over a finite field"
                  if any_singular else
                  "no singular point over %d prime(s); evidence, not proof "
                  "in characteristic zero" % used)

    return {
        "smooth": smooth,
        "proof": False,
        "reason": reason,
        "primes_used": used,
        "per_prime": per_prime,
        "singular_example": witness,
        "generic": generic,
    }
